print('I feel alot better now')
print("I think it really was just the blues")
print("Ang embarassing pala write ito sa public git")
print("not like anyone's gonna go through this shi lmao")
print("Code nalang me something")
num = int(input("Enter a number: "))
num2 = int(input("Enter a 2nd number: "))
