import time
import os

os.system('cls')
print("*Breathes in")
print("")
time.sleep(1)
print("sigh.")
time.sleep(1)
os.system('cls')
print("*Breathes in")
print("")
print("sigh..")
time.sleep(1)
os.system('cls')
print("*Breathes in")
print("")
print("sigh...")
time.sleep(3)
print("")
print("I'm kinda tired")
print("")
time.sleep(2)
print("I've been at it so I'll wake up when I feel 'fine")
time.sleep(2)
print("")
print("Whatever.")
time.sleep(1)
os.system('cls')
print("*Breathes in")
print("")
print("sigh...")
time.sleep(1)
os.system('cls')
print("")
print("I'm kinda tired")
print("")
print("I've been at it so I'll wake up when I feel 'fine")
print("")
print("Whatever..")
time.sleep(1)
os.system('cls')
print("*Breathes in")
print("")
print("sigh...")
print("")
print("I'm kinda tired")
print("")
print("I've been at it so I'll wake up when I feel 'fine")
print("")
print("Whatever...")
time.sleep(2)
os.system('cls')
print("*Breathes in")
print("")
print("sigh...")
print("")
print("I'm kinda tired")
print("")
print("I've been at it so I'll wake up when I feel 'fine")
print("")
print("Whatever...'fine' is exactly")
time.sleep(2)
print("")
print("I'll be fine.")
time.sleep(2)
print("")
print("Thanks for being concerned")