import time
import os

os.system('cls')
print("*Breathes in")
print("")
time.sleep(1)
print("sigh.")
time.sleep(1)
os.system('cls')
print("*Breathes in")
print("")
print("sigh..")
time.sleep(1)
os.system('cls')
print("*Breathes in")
print("")
print("sigh...")
time.sleep(3)
print("")
print("I'm kinda tired")
print("")
time.sleep(2)
print("I've been at it so I'll wake up when I feel 'fine")

