print("Suddenly")
print("A semester passed by just like that")
print("Kinda scary how events will unfold")
print("Honestly, I think well I hope everything's gonna be fine with you with me")
print("Hopefully that is, would you like me how I like you back?")
print("S")