print('hehe')
print('this is kinda cheating')
print('going back')
print('sup')
print('1/20/2025')
print(223)
print(function)
print('sana')
print('kineme')
print('here')
print('hey')
123
3
print("if you're seeing this")
print('cheating')
print('uga ngani')
print(1+2)
