import time
import os
import math
os.system('cls')
print("*Breathes in")
print("")
time.sleep(1)
print("sigh.")
time.sleep(1)
os.system('cls')
print("*Breathes in")
print("")
print("sigh..")
time.sleep(1)
os.system('cls')
print("*Breathes in")
print("")
print("sigh...")
time.sleep(1)
os.system('cls')
print("*Breathes in")
print("")
print("sigh...I'm kinda tired")
time.sleep(2)
print("")
print("I've been at it so I'll wake up when I feel 'fine'")
time.sleep(2)
print("")
print("Whatever.")
time.sleep(1)
os.system('cls')
print("*Breathes in")
print("")
print("sigh...I'm kinda tired")
print("")
print("I've been at it so I'll just sleep and wake up till I feel 'fine'")
print("")
print("Whatever..")
time.sleep(1)
os.system('cls')
print("*Breathes in")
print("")
print("sigh...I'm kinda tired")
print("")
print("I've been at it so I'll jjust sleep and wake up till I feel 'fine")
print("")
print("Whatever...")
time.sleep(1)
os.system('cls')
print("*Breathes in")
print("")
print("sigh...I'm kinda tired")
print("")
print("I've been at it so I'll just sleep and wake up till I feel 'fine")
print("")
print("Whatever...'fine' means exactly")
time.sleep(2)
print("")
print("I'll be fine.")
time.sleep(2)
print("")
print("Thanks for being concerned")
